### ISSUE TITLE
Null Pointer Exception on server startup

### ISSUE THREAD

**Issue by RikuKawai** [jusdino/BuildPortals#13]
```
[20:33:36] [Server thread/ERROR]: Error occurred while enabling BuildPortals v1.18.18 (Is it up to date?)
java.lang.NullPointerException: null
	at frahm.justin.mcplugins.buildportals.PortalFactory.loadFromConfig(PortalHandler.java:1078) ~[?:?]
	at frahm.justin.mcplugins.buildportals.PortalHandler.updatePortals(PortalHandler.java:453) ~[?:?]
	at frahm.justin.mcplugins.buildportals.Main.onEnable(Main.java:41) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[20:33:36] [Server thread/INFO]: [BuildPortals] Disabling BuildPortals v1.18.18

```
Started getting this error on server startup, tried rolling back to PaperMC 1615 and still had the same error. Nothing changed on the server it just started happening.

**Comment by jusdino** [comment]
Can you post your `BuildPortals/config.yml`?

**Comment by RikuKawai** [comment]
[config.zip](https://github.com/jusdino/BuildPortals/files/3414115/config.zip)

Zipped cause GitHub wouldn't take a YML file.
I figured it might be a bad portal in the config, I think there's some in there still which point to worlds that don't exist anymore.

**Comment by jusdino** [comment]
Usually, I've seen missing worlds fail differently. What multi-world plugin are you using?

**Comment by RikuKawai** [comment]
The original Multiworld, which technically isn't supported anymore, but is supported for 1.12.2 which I'm running.

**Comment by jusdino** [comment]
Yeah, I'd be surprised if Multiworld was a problem for you on 1.12.2.

**Comment by jusdino** [comment]
Nothing is jumping out at me right away. I haven't played with PaperMC yet though. I'll have to dig into this some more. Would you mind packaging up all of your server files and sending them this way so I can try to figure it out?

**Comment by RikuKawai** [comment]
Zipping it up now, left out the worlds because it would be almost 60GB, but you should be able to reproduce the error without my worlds.

**Comment by jusdino** [comment]
Sounds good.

Are these all actual world names?
DestinationHub
Americant
Sever map
world
ericsan
Sever map_nether
Sever map_the_end

One thing to try would be to remove any portals in the .yml file that reference one of the worlds above if it isn't there anymore just to see if it is actually erroring out in an unusual way with a missing world.

**Comment by RikuKawai** [comment]
Only DestinationHub, Americant, and ericsan still exist, I'll go through and try to remove references to the other ones which don't exist anymore.

Also here's the server stripped of worlds (and the coreprotect db) https://mega.nz/#!ad0jlSpJ!U1PoISWHaBtoO4SRfVQO2-hy6QD5_0JqYALXLxGLHsY

**Comment by RikuKawai** [comment]
I removed the unused portals and it still fails to load the plugin with the same error, so it's something else.

**Comment by jusdino** [comment]
Okay, mind trying this snapshot build to confirm if it fixes your issue?
https://frahm.pw/BuildPortals-1.18.115-SNAPSHOT.jar

**Comment by RikuKawai** [comment]
The plugin loads and functions correctly now. What was the issue?

**Comment by jusdino** [comment]
Awesome. So, when loading sides A and B of a portal from config, I had a check that `worldB` was located by name properly but evidently forgot to do the same for `worldA`. If `worldA` didn't exist, it would throw that `NullPointerException` instead of failing gracefully.

**Comment by RikuKawai** [comment]
I think I understand what happened then. Sometimes the portals stop working and need to be forcefully updated by activating one of them, which normally happens before the next time the server is restarted. However in this case my server restarted itself due to an unrelated crash, leaving BuildPortals in this state which would then refuse to load.
