### ISSUE TITLE
every time a player is standing in a portal, they will not go through and this will spam the console until they leave the portal

### ISSUE THREAD

**Issue by xcomcadx** [jusdino/BuildPortals#46]
[18:57:00 WARN]: [BuildPortals] Global task for BuildPortals v2.2.0 generated an exception
java.lang.NullPointerException: Cannot invoke "io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.getData()" because the return value of "dev.rgbmc.folia.CachedRegionData.getWorld(String)" is null
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:849) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:230) ~[?:?]
        at net.minecraft.world.level.Level.getChunk(Level.java:509) ~[?:?]
        at net.minecraft.world.level.Level.getBlockState(Level.java:806) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:240) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at space.frahm.buildportals.AbstractPortal.integrityCheck(AbstractPortal.java:40) ~[BuildPortals-2.2.0.jar:?]
        at space.frahm.buildportals.Portal.teleport(Portal.java:140) ~[BuildPortals-2.2.0.jar:?]
        at space.frahm.buildportals.PortalListener$1.run(PortalListener.java:76) ~[BuildPortals-2.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.lambda$handle$8(CraftScheduler.java:594) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:310) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:165) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:388) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by jusdino** [comment]
@xcomcadx , thanks for the report. Can you get some more detail for how to reproduce this? What server (and version) are you running?
